
include ~/.cache/wal/colors-kitty.conf
# font_family Qurova DEMO
# font_family MonoLisa
# font_family Space Mono
# font_family Pixel Code
font_family Monocraft 
# font_family minecraft 
# font_family PP Gosha Sans
window_padding_width 10
font_size 16
font_weight 800

bold_font auto
italic_font auto
bold_italic_font auto
# Прозрачность и размытие
background_opacity 0.90

background_blur 1
shell /bin/zsh
#жирный шрифт



